# Generated by Django 5.2.8 on 2025-12-07 12:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mascotas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='interaccion',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interacciones', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mascota',
            name='protectora',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mascotas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='interaccion',
            name='mascota',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interacciones', to='mascotas.mascota'),
        ),
        migrations.AlterUniqueTogether(
            name='interaccion',
            unique_together={('usuario', 'mascota')},
        ),
    ]
