# Generated by Django 5.2.6 on 2025-11-23 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mascota',
            name='protectoraEncargada',
        ),
    ]
