# Generated by Django 5.2.8 on 2025-11-29 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascota',
            name='descripcion',
            field=models.TextField(blank=True, help_text='Descripción generada automáticamente o personalizada', null=True, verbose_name='Biografía de la mascota'),
        ),
    ]
