# Generated by Django 5.2.8 on 2025-12-10 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0003_add_descripcion_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascota',
            name='foto2',
            field=models.ImageField(blank=True, null=True, upload_to='mascotas/', verbose_name='Foto 2'),
        ),
        migrations.AddField(
            model_name='mascota',
            name='foto3',
            field=models.ImageField(blank=True, null=True, upload_to='mascotas/', verbose_name='Foto 3'),
        ),
    ]
