# Generated by Django 5.2.8 on 2025-12-13 19:09

import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0004_mascota_foto2_mascota_foto3'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascota',
            name='apto_ninos',
            field=models.CharField(choices=[('APTO_NINOS', 'Apto para convivir con niños'), ('NO_APTO_NINOS', 'Solo adultos / No apto para niños'), ('INDIFERENTE_NINOS', 'Indiferente / Sin preferencia')], default='INDIFERENTE_NINOS', max_length=20, verbose_name='Compatibilidad con niños'),
        ),
        migrations.AddField(
            model_name='mascota',
            name='necesita_compania_animal',
            field=models.CharField(choices=[('PUEDE_SOLO', 'Puede vivir solo (sin otros animales)'), ('NECESITA_COMPANIA', 'Necesita compañía de otro animal'), ('INDIFERENTE_COMPANIA', 'Indiferente / Se adapta')], default='INDIFERENTE_COMPANIA', max_length=25, verbose_name='Necesidad de compañía animal'),
        ),
        migrations.AddField(
            model_name='mascota',
            name='nivel_experiencia',
            field=models.CharField(choices=[('PRIMERIZOS', 'Apto para dueños primerizos'), ('EXPERIENCIA', 'Requiere dueños con experiencia'), ('LICENCIA_PPP', 'Requiere licencia PPP'), ('INDIFERENTE_EXP', 'Indiferente / Sin requisito especial')], default='INDIFERENTE_EXP', max_length=20, verbose_name='Nivel de experiencia requerido'),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='apto_con',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('NINOS', 'Apto para convivir con niños'), ('SIN_NINOS', 'Solo adultos / No apto para niños'), ('PERROS', 'Perros (Apto con introducción lenta)'), ('GATOS', 'Gatos (Apto con gatos tranquilos)'), ('SOLO_EL', 'Hogar sin otros animales/Exclusivo'), ('COMPANIA_OBLIGATORIA', 'Compañía Felina/Canina Obligatoria'), ('PRIMERIZOS', 'Dueños Primerizos'), ('EXPERIENCIA', 'Dueños con Experiencia'), ('DUEÑOS_PPP', 'Dueños con Licencia PPP (Para Perros Potencialmente Peligrosos)')], max_length=150, verbose_name='[LEGACY] Apto para Convivir con'),
        ),
    ]
