# Generated by Django 5.2.8 on 2025-11-27 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0004_remove_mascota_peso_remove_mascota_tamaño'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascota',
            name='tamaño',
            field=models.CharField(choices=[('pequeño', 'Pequeño (0-10kg)'), ('mediano', 'Mediano (10-25kg)'), ('grande', 'Grande (25-45kg)'), ('gigante', 'Gigante (+45kg)')], default='mediano', max_length=20, verbose_name='Tamaño'),
        ),
    ]
