# Generated by Django 5.2.8 on 2025-12-15 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0005_mascota_apto_ninos_mascota_necesita_compania_animal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascota',
            name='convivencia_animales',
            field=models.CharField(blank=True, choices=[('', '---'), ('si', 'Sí'), ('no', 'No')], max_length=20, null=True, verbose_name='Compatible con otros animales'),
        ),
        migrations.AddField(
            model_name='mascota',
            name='convivencia_ninos',
            field=models.CharField(blank=True, choices=[('', '---'), ('si', 'Sí'), ('no', 'No')], max_length=10, null=True, verbose_name='Compatible con niños'),
        ),
    ]
