# Generated by Django 5.2.6 on 2025-11-30 21:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Introduzca el nombre del animal', max_length=100, verbose_name='Nombre')),
                ('especie', models.CharField(choices=[('perro', 'Perro'), ('gato', 'Gato')], default='gato', max_length=10, verbose_name='Especie')),
                ('raza_perro', models.CharField(choices=[('mestizo', 'Mestizo'), ('labrador', 'Labrador Retriever'), ('pastor_aleman', 'Pastor Alemán'), ('bulldog', 'Bulldog Inglés'), ('beagle', 'Beagle'), ('siames', 'Siamés'), ('persa', 'Persa')], default='mestizo', max_length=150, verbose_name='Raza')),
                ('raza_gato', models.CharField(choices=[('mestizo', 'Mestizo'), ('siames', 'Siamés'), ('persa', 'Persa')], default='mestizo', max_length=150, verbose_name='Raza')),
                ('genero', models.CharField(choices=[('macho', 'Macho'), ('hembra', 'Hembra')], default='hembra', max_length=10, verbose_name='Género')),
                ('edad', models.PositiveIntegerField(default=0, help_text='Edad en años', verbose_name='Edad')),
                ('tamaño', models.CharField(choices=[('pequeño', 'Pequeño (0-10kg)'), ('mediano', 'Mediano (10-25kg)'), ('grande', 'Grande (25-45kg)'), ('gigante', 'Gigante (+45kg)')], default='mediano', max_length=20, verbose_name='Tamaño')),
                ('color', models.CharField(default='marrón', max_length=100, verbose_name='Color')),
                ('foto', models.ImageField(upload_to='mascotas/', verbose_name='Foto')),
                ('caracter', models.CharField(choices=[('cariñoso', 'Cariñoso'), ('jugueton', 'Juguetón'), ('tranquilo', 'Tranquilo'), ('activo', 'Activo'), ('sociable', 'Sociable'), ('independiente', 'Independiente'), ('protector', 'Protector'), ('timido', 'Tímido'), ('obediente', 'Obediente')], default='cariñoso', max_length=20, verbose_name='Carácter')),
                ('convivencia_animales', models.CharField(choices=[('no', 'No puede convivir con otros animales'), ('misma_especie', 'Solo con animales de su misma especie'), ('cualquier_especie', 'Puede convivir con cualquier animal')], default='no', max_length=20, verbose_name='¿Puede convivir con otros animales?')),
                ('convivencia_ninos', models.BooleanField(default=False, verbose_name='¿Puede convivir con niños?')),
                ('desparasitado', models.BooleanField(default=False, help_text='¿Está desparasitado?')),
                ('esterilizado', models.BooleanField(default=False, help_text='¿Está esterilizado?')),
                ('con_microchip', models.BooleanField(default=False, help_text='¿Tiene microchip?')),
                ('vacunado', models.BooleanField(default=False, help_text='¿Está vacunado?')),
                ('necesidades_especiales', models.BooleanField(default=False, verbose_name='¿Tiene necesidades especiales?')),
                ('descripcion_necesidades', models.TextField(blank=True, null=True, verbose_name='Descripción de necesidades especiales')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción generada automáticamente o personalizada', null=True, verbose_name='Biografía de la mascota')),
                ('ubicacion', models.CharField(default='Barcelona', help_text='Ciudad/ubicación heredada de la protectora', max_length=100, verbose_name='Ubicación')),
                ('adoptado', models.BooleanField(default=False)),
                ('oculto', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('protectora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mascotas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mascota',
                'verbose_name_plural': 'Mascotas',
                'db_table': 'mascotas',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Interaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('L', 'Me interesa'), ('D', 'No me interesa')], max_length=1, verbose_name='Acción (L/D)')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(help_text='Usuario adoptante que realiza la acción.', on_delete=django.db.models.deletion.CASCADE, related_name='interacciones_realizadas', to=settings.AUTH_USER_MODEL)),
                ('mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interacciones_recibidas', to='mascotas.mascota')),
            ],
            options={
                'verbose_name': 'Interacción de Swipe',
                'verbose_name_plural': 'Interacciones de Swipes',
                'db_table': 'interacciones_swipe',
                'unique_together': {('usuario', 'mascota')},
            },
        ),
    ]
