# Generated by Django 5.2.8 on 2025-12-07 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascota',
            name='descripcion',
            field=models.TextField(blank=True, help_text='Descripción del animal, puede ser generada automáticamente por IA', null=True, verbose_name='Descripción/Biografía'),
        ),
    ]
