# Generated by Django 5.2.8 on 2025-11-26 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0003_remove_mascota_protectoraencargada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mascota',
            name='peso',
        ),
        migrations.RemoveField(
            model_name='mascota',
            name='tamaño',
        ),
    ]
