# Generated by Django 5.2.8 on 2025-11-29 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0003_mascota_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascota',
            name='ubicacion',
            field=models.CharField(default='Barcelona', help_text='Ciudad/ubicación heredada de la protectora', max_length=100, verbose_name='Ubicación'),
        ),
    ]
