# Generated by Django 5.2.6 on 2025-11-27 22:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0005_mascota_tamaño'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Interaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('L', 'Me interesa'), ('D', 'No me interesa')], max_length=1, verbose_name='Acción (L/D)')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interacciones_recibidas', to='mascotas.mascota')),
                ('usuario', models.ForeignKey(help_text='Usuario adoptante que realiza la acción.', on_delete=django.db.models.deletion.CASCADE, related_name='interacciones_realizadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Interacción de Swipe',
                'verbose_name_plural': 'Interacciones de Swipes',
                'db_table': 'interacciones_swipe',
                'unique_together': {('usuario', 'mascota')},
            },
        ),
    ]
