# Generated by Django 5.2.8 on 2025-12-03 17:40

import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0005_mascota_tamaño'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mascota',
            name='caracter',
        ),
        migrations.RemoveField(
            model_name='mascota',
            name='color',
        ),
        migrations.RemoveField(
            model_name='mascota',
            name='con_microchip',
        ),
        migrations.RemoveField(
            model_name='mascota',
            name='convivencia_animales',
        ),
        migrations.RemoveField(
            model_name='mascota',
            name='convivencia_ninos',
        ),
        migrations.RemoveField(
            model_name='mascota',
            name='descripcion_necesidades',
        ),
        migrations.RemoveField(
            model_name='mascota',
            name='desparasitado',
        ),
        migrations.RemoveField(
            model_name='mascota',
            name='esterilizado',
        ),
        migrations.RemoveField(
            model_name='mascota',
            name='necesidades_especiales',
        ),
        migrations.RemoveField(
            model_name='mascota',
            name='tamaño',
        ),
        migrations.RemoveField(
            model_name='mascota',
            name='vacunado',
        ),
        migrations.AddField(
            model_name='mascota',
            name='apto_con',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('NINOS', 'Apto para convivir con niños'), ('SIN_NINOS', 'Solo adultos / No apto para niños'), ('PERROS', 'Perros (Apto con introducción lenta)'), ('GATOS', 'Gatos (Apto con gatos tranquilos)'), ('SOLO_EL', 'Hogar sin otros animales/Exclusivo'), ('COMPANIA_OBLIGATORIA', 'Compañía Felina/Canina Obligatoria'), ('PRIMERIZOS', 'Dueños Primerizos'), ('EXPERIENCIA', 'Dueños con Experiencia'), ('DUEÑOS_PPP', 'Dueños con Licencia PPP (Para Perros Potencialmente Peligrosos)')], max_length=150, verbose_name='Apto para Convivir con'),
        ),
        migrations.AddField(
            model_name='mascota',
            name='caracter_gato',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('CARINOSO', 'Cariñoso / Afectivo'), ('FALDERO', 'Faldero / Buscador de Mimos'), ('DEPENDIENTE', 'Dependiente / Necesita Compañía'), ('INDEPENDIENTE', 'Independiente / Solitario'), ('TIMIDO', 'Tímido / Cauteloso / Se Esconde'), ('ASUSTADIZO', 'Asustadizo / Nervioso'), ('JUGUETON', 'Juguetón (Moderado)'), ('JUGUETON_INTENSO', 'Juguetón Intenso / Hiperactivo'), ('ACTIVO', 'Activo / Enérgico / Aventurero'), ('TRANQUILO', 'Tranquilo / Baja Energía / Perezoso'), ('CAZADOR', 'Cazador'), ('SOCIABLE', 'Sociable / Amigable (Con todos)'), ('AFECTIVO_CONOCIDOS', 'Afectivo (Solo con conocidos)'), ('HABALADOR', 'Hablador / Expresivo'), ('TERRITORIAL', 'Territorial / Mandón (Bossy)'), ('SEMIFERAL', 'Semiferal / No Doméstico'), ('OBSERVADOR', 'Observador / Curioso'), ('ADAPTABLE', 'Adaptable / Estable'), ('DIVA', 'Diva / Carácter Fuerte / Posesivo'), ('LIMPIO', 'Limpio')], max_length=250, verbose_name='Carácter y Personalidad'),
        ),
        migrations.AddField(
            model_name='mascota',
            name='caracter_perro',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('CARINOSO', 'Cariñoso / Afectivo'), ('FALDERO', 'Faldero'), ('DEPENDIENTE', 'Dependiente (Necesita Compañía Constante)'), ('DUO_INSEPARABLE', 'Dúo / Hermanos Inseparables (Adopción Conjunta)'), ('TIMIDO', 'Tímido / Reservado / Baja Confianza'), ('MIEDOSO', 'Miedoso / Nervioso'), ('JUGUETON', 'Juguetón / Travieso'), ('ACTIVO_ENERGICO', 'Activo / Enérgico / Hiperactivo'), ('TRANQUILO', 'Tranquilo / Pacífico / Lento'), ('TRABAJADOR', 'Trabajador / Necesita Misión'), ('SOCIABLE', 'Sociable / Familiar (Apto con Personas y Perros)'), ('PROTECTOR_GUARDIAN', 'Protector / Guardián / Fuerte Instinto de Alerta'), ('DOMINANTE_PERROS', 'Dominante / Territorial (Hacia otros Perros)'), ('REACTIVO', 'Reactivo (Necesita Bozal o Doble Correa para Paseos)'), ('LIDERAZGO', 'Necesita Liderazgo y Entrenamiento Firme'), ('DESCONFIADO_EXTRANOS', 'Desconfiado (Hacia Extraños)'), ('OBEDIENTE', 'Obediente (Requiere Consistencia)'), ('OLAFATEADOR', 'Olfateador / Instinto de Caza Alto'), ('LADRADOR', 'Ladrador (Fácil o Moderado)'), ('ESCAPISTA', 'Escapista / Tendencia a Aullar'), ('EXCAVADOR', 'Excavador'), ('GLOTON', 'Glotón / Obsesión por Comida'), ('CABEZOTA', 'Cabezota / Independiente'), ('INTELIGENTE', 'Inteligente / Necesidad de Estimulación Mental'), ('SENSIBLE', 'Sensible / Oídos Sensibles'), ('LEAL', 'Leal')], max_length=350, verbose_name='Carácter, Instinto y Necesidad de Manejo'),
        ),
        migrations.AddField(
            model_name='mascota',
            name='color_pelaje_gato',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('NEGRO', 'Negro'), ('BLANCO', 'Blanco Puro'), ('GRIS_AZUL', 'Gris / Azul Sólido'), ('ROJO_NARANJA', 'Rojo / Naranja (Ginger / Melocotón)'), ('CREMA', 'Crema'), ('MARRON', 'Marrón'), ('ATIGRADO', 'Atigrado (Tabby)'), ('MOTEADO', 'Moteado (Spotted Tabby)'), ('BICOLOR', 'Bicolor / Manchas'), ('TRICOLOR_CALICO', 'Tricolor / Calicó'), ('CAREY', 'Carey (Tortoiseshell)'), ('POINT_OSCURO', 'Seal Point (Puntas Oscuras)'), ('POINT_AZUL', 'Point Azul'), ('POINT_CREMA', 'Point Crema (Muted)')], max_length=150, verbose_name='Color y Patrón de Pelaje del Gato'),
        ),
        migrations.AddField(
            model_name='mascota',
            name='color_pelaje_perro',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('NEGRO', 'Negro Sólido'), ('BLANCO', 'Blanco Sólido'), ('MARRON', 'Marrón / Chocolate'), ('GRIS_AZUL', 'Gris / Azul Sólido'), ('DORADO_LEONADO', 'Dorado / Amarillo / Leonado'), ('CANELA_ROJIZO', 'Canela / Rojo / Fuego (Tan)'), ('ATIGRADO', 'Atigrado (Brindle)'), ('TRICOLOR', 'Tricolor (Negro, Blanco, Canela)'), ('BICOLOR', 'Bicolor / Manchas'), ('MOTEADO', 'Moteado (Ticking)'), ('MERLE', 'Merle (Azul o Rojo)')], max_length=150, verbose_name='Color y Patrón de Pelaje del Perro'),
        ),
        migrations.AddField(
            model_name='mascota',
            name='condicion_especial_gato',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('DIABETES', 'Diabetes Mellitus (Requiere Insulina/Dieta)'), ('RENAL_CRONICA', 'Enfermedad Renal Crónica'), ('HIPERTIROIDISMO', 'Hipertiroidismo (Controlado con medicación)'), ('CARDIACA', 'Insuficiencia Cardíaca Congestiva (Controlada)'), ('EPILEPSIA', 'Epilepsia Controlada'), ('FIP_RECUPERACION', 'Recuperación de Peritonitis Infecciosa Felina (FIP)'), ('FIV_POSITIVO', 'Inmunodeficiencia Felina (FIV Positivo)'), ('SORDERA', 'Sordera Total o Parcial'), ('CEGUERA', 'Ceguera Total o Parcial'), ('HIPOPLASIA_CEREBELAR', 'Hipoplasia Cerebelar (Ataxia)'), ('PARAPARESIA', 'Parálisis Parcial/Total (Paraparesia)'), ('AMPUTACION', 'Amputación o Falta de Extremidades'), ('OSTEOARTRITIS', 'Osteoartritis Severa/Problemas Articulares'), ('PROBLEMAS_RESPIRATORIOS', 'Problemas Respiratorios Crónicos (Braquicefalia)'), ('DISPLASIA', 'Osteocondrodisplasia (Articulaciones Rígidas)'), ('PIEL_CRONICA', 'Dermatitis/Cuidados de Piel Específicos'), ('DENTAL_CRONICA', 'Problemas Dentales Crónicos/Periodontitis'), ('INCONTINENCIA', 'Incontinencia Urinaria Crónica'), ('OBESIDAD_CRONICA', 'Obesidad Crónica (Bulimia/Dieta Estricta)'), ('TIMIDEZ_EXTREMA', 'Timidez Extrema / No Sociable'), ('SEMIFERAL', 'Semiferal / No Doméstico'), ('CARACTER_FUERTE', 'Carácter Fuerte / Alfa (Intolerancia a otros animales)')], max_length=300, verbose_name='Condición o Necesidad Especial del Gato'),
        ),
        migrations.AddField(
            model_name='mascota',
            name='condicion_especial_perro',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('ANSIEDAD_SEPARACION', 'Ansiedad por Separación (Severa)'), ('REACTIVIDAD', 'Reactividad (Miedo, Territorialidad o Hacia Otros Perros)'), ('MIEDO_RUIDOS', 'Miedo a Ruidos Fuertes/Fuegos Artificiales'), ('MIEDO_PERSONAS', 'Miedo a Personas Desconocidas o Hombres'), ('ESCAPE', 'Tendencia al Escapismo'), ('SECUELAS_ABUSO', 'Secuelas de Abuso Físico/Timidez Crónica'), ('DEPENDENCIA_DUO', 'Dependencia Emocional/Adopción Conjunta Obligatoria'), ('DISPLASIA_CADERA', 'Displasia de Cadera o Codo'), ('OSTEOARTRITIS', 'Osteoartritis/Artritis Geriátrica'), ('PROBLEMAS_COLUMNA', 'Problemas de Columna'), ('AMPUTACION', 'Amputación o Falta de Extremidades'), ('MOVILIDAD_SENIOR', 'Problemas de Movilidad (Senior)'), ('CARDIACA', 'Insuficiencia Cardíaca Congestiva (Controlada)'), ('EPILEPSIA', 'Epilepsia Controlada'), ('CUSHING', 'Síndrome de Cushing (Hiperadrenocorticismo)'), ('HIPOPLASIA_CEREBELAR', 'Hipoplasia Cerebelar (Ataxia)'), ('BRAQUICEFALICO', 'Síndrome Braquicefálico/Problemas Respiratorios Crónicos'), ('COLAPSO_TRAQUEAL', 'Colapso Traqueal'), ('PROBLEMAS_OIDO', 'Problemas de Oído Crónicos'), ('CATARATAS', 'Cataratas (Geriátricas o Congénitas)'), ('ALERGIA_ALIMENTARIA', 'Alergia Alimentaria Múltiple/Dieta Estricta'), ('DERMATITIS', 'Dermatitis/Alergia Cutánea Crónica'), ('DENTAL_CRONICA', 'Problemas Dentales Crónicos'), ('INCONTINENCIA', 'Incontinencia Urinaria Crónica'), ('SOBREPESO', 'Sobrepeso/Obesidad Crónica')], max_length=350, verbose_name='Condición o Necesidad Especial del Perro'),
        ),
        migrations.AddField(
            model_name='mascota',
            name='edad_clasificacion',
            field=models.CharField(choices=[('0', 'Menos de 1 año'), ('1_2', '1-2 años (Joven)'), ('3_6', '3-6 años (Adulto)'), ('7_10', '7-10 años (Adulto Maduro)'), ('11_14', '11-14 años (Senior)'), ('15_MAS', '15 años o más (Ultra Senior)')], default='3_6', max_length=10, verbose_name='Clasificación de Edad'),
        ),
        migrations.AddField(
            model_name='mascota',
            name='estado_legal_salud',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('DESPARASITADO', 'Desparasitado Interna y Externamente'), ('ESTERILIZADO', 'Esterilizado/Castrado'), ('VACUNADO', 'Vacunado'), ('MICROCHIP', 'Identificado con Microchip')], max_length=50, verbose_name='Estado de Salud y Legal'),
        ),
        migrations.AddField(
            model_name='mascota',
            name='tamano',
            field=models.CharField(choices=[('PEQUENO', 'Pequeño (Hasta 10kg)'), ('MEDIANO', 'Mediano (10-25kg)'), ('GRANDE', 'Grande (25-45kg)'), ('GIGANTE', 'Gigante (Más de 45kg)')], default='MEDIANO', max_length=10, verbose_name='Tamaño'),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='especie',
            field=models.CharField(choices=[('PERRO', 'Perro'), ('GATO', 'Gato')], default='GATO', max_length=10, verbose_name='Especie'),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='genero',
            field=models.CharField(choices=[('MACHO', 'Macho'), ('HEMBRA', 'Hembra')], default='HEMBRA', max_length=10, verbose_name='Género'),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='raza_gato',
            field=models.CharField(choices=[('MESTIZO', 'Mestizo / Cruce'), ('SPHYNX', 'Esfinge (Sphynx)'), ('EUROPEO', 'Europeo'), ('ANGORA_TURCO', 'Angora Turco'), ('SIAMES', 'Siamés'), ('PERSA', 'Persa'), ('BENGAL', 'Bengal'), ('SIBERIANO', 'Siberiano'), ('SCOTTISH_FOLD', 'Scottish Fold'), ('AZUL_RUSO', 'Azul Ruso'), ('MAINE_COON', 'Maine Coon'), ('BOSQUE_NORUEGA', 'Bosque de Noruega'), ('TAILANDES', 'Tailandés (Wichian Mat)'), ('DEVON_REX', 'Devon Rex'), ('RAGDOLL', 'Ragdoll'), ('ORIENTAL', 'Oriental'), ('ABISINIO', 'Abisinio')], default='MESTIZO', max_length=20, verbose_name='Raza del Gato'),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='raza_perro',
            field=models.CharField(choices=[('MESTIZO', 'Mestizo / Cruce'), ('LABRADOR', 'Labrador Retriever'), ('GOLDEN_RETRIEVER', 'Golden Retriever'), ('PASTOR_ALEMAN', 'Pastor Alemán'), ('HUSKY', 'Husky Siberiano / Malamute'), ('BEAGLE', 'Beagle'), ('BORDER_COLLIE', 'Border Collie'), ('ROTTWEILER', 'Rottweiler'), ('PITBULL', 'Pitbull / Amstaff'), ('TECKEL', 'Teckel (Salchicha / Dachshund)'), ('POODLE', 'Caniche (Poodle)'), ('BICHON', 'Bichón (Maltés / Frisé)'), ('CHIHUAHUA', 'Chihuahua / Pincher'), ('YORKSHIRE_TERRIER', 'Yorkshire Terrier'), ('POMERANIA', 'Pomerania'), ('MASTIN', 'Mastín (Español, Napolitano, etc.)'), ('BULLDOG_FRANCES', 'Bulldog Francés'), ('AKITA_INU', 'Akita Inu'), ('DOBERMAN', 'Dóberman'), ('BOXER', 'Bóxer'), ('COCKER_SPANIEL', 'Cocker Spaniel'), ('GALGO', 'Galgo (Español / Greyhound / Lurcher)'), ('DOGO_ARGENTINO', 'Dogo Argentino'), ('SAN_BERNARDO', 'San Bernardo'), ('CAREA', 'Carea (Leonés / Vasco)'), ('PODENCO', 'Podenco'), ('GRAN_DANES', 'Gran Danés'), ('CORGI', 'Corgi'), ('SHIH_TZU', 'Shih Tzu'), ('SAMOYEDO', 'Samoyedo'), ('MALINOIS', 'Pastor Belga Malinois'), ('JACK_RUSSELL', 'Jack Russell Terrier'), ('SETTER_INGLES', 'Setter Inglés'), ('PEKINES', 'Pekinés / Lhasa Apso')], default='MESTIZO', max_length=20, verbose_name='Raza del Perro'),
        ),
    ]
