# Generated by Django 5.2.6 on 2025-11-23 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilprotectora',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('usuario', 'Usuario'), ('protectora', 'Protectora')], default='protectora', editable=False, max_length=20),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('usuario', 'Usuario'), ('protectora', 'Protectora')], default='usuario', editable=False, max_length=20),
        ),
        migrations.AddField(
            model_name='usuario',
            name='city',
            field=models.CharField(default='Barcelona', max_length=100),
        ),
    ]
