# Generated by Django 5.2.8 on 2025-12-03 17:40

import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_perfilprotectora_role_perfilusuario_role_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfilusuario',
            name='deporte_ofrecible',
        ),
        migrations.RemoveField(
            model_name='perfilusuario',
            name='especie',
        ),
        migrations.RemoveField(
            model_name='perfilusuario',
            name='mascota_previa',
        ),
        migrations.RemoveField(
            model_name='perfilusuario',
            name='necesidades_especiales',
        ),
        migrations.RemoveField(
            model_name='perfilusuario',
            name='nivel_actividad_familiar',
        ),
        migrations.RemoveField(
            model_name='perfilusuario',
            name='tiempo_en_casa_para_gatos',
        ),
        migrations.RemoveField(
            model_name='perfilusuario',
            name='tiene_ninos',
        ),
        migrations.RemoveField(
            model_name='perfilusuario',
            name='tipo_vivienda',
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='acepta_condicion_especial',
            field=models.BooleanField(default=False, help_text="Marque 'Sí' si está dispuesto a adoptar una mascota que requiera cuidados extra (medicación, dieta especial, o condición crónica).", verbose_name='¿Acepta mascotas con condiciones o necesidades especiales?'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='preferencias_convivencia',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('NINOS', 'Apto para convivir con niños'), ('SIN_NINOS', 'Solo adultos / No apto para niños'), ('PERROS', 'Perros (Apto con introducción lenta)'), ('GATOS', 'Gatos (Apto con gatos tranquilos)'), ('SOLO_EL', 'Hogar sin otros animales/Exclusivo'), ('COMPANIA_OBLIGATORIA', 'Compañía Felina/Canina Obligatoria'), ('PRIMERIZOS', 'Dueños Primerizos'), ('EXPERIENCIA', 'Dueños con Experiencia'), ('DUEÑOS_PPP', 'Dueños con Licencia PPP (Para Perros Potencialmente Peligrosos)')], max_length=200, verbose_name='Apto para Convivir con (Búsqueda)'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='preferencias_estado_basico',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('DESPARASITADO', 'Desparasitado Interna y Externamente'), ('ESTERILIZADO', 'Esterilizado/Castrado'), ('VACUNADO', 'Vacunado'), ('MICROCHIP', 'Identificado con Microchip')], max_length=100, verbose_name='Estado de Salud/Legal Mínimo'),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='preferencias_edad',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('0', 'Menos de 1 año'), ('1_2', '1-2 años (Joven)'), ('3_6', '3-6 años (Adulto)'), ('7_10', '7-10 años (Adulto Maduro)'), ('11_14', '11-14 años (Senior)'), ('15_MAS', '15 años o más (Ultra Senior)')], max_length=27, verbose_name='Edad(es) Preferida(s)'),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='preferencias_sexo',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('MACHO', 'Macho'), ('HEMBRA', 'Hembra')], max_length=12, verbose_name='Sexo Preferido'),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='preferencias_tamano',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('PEQUENO', 'Pequeño (Hasta 10kg)'), ('MEDIANO', 'Mediano (10-25kg)'), ('GRANDE', 'Grande (25-45kg)'), ('GIGANTE', 'Gigante (Más de 45kg)')], max_length=30, verbose_name='Tamaño(s) Preferido(s)'),
        ),
    ]
