# Generated by Django 5.2.6 on 2025-11-23 15:32

import django.contrib.auth.models
import django.db.models.deletion
import django.utils.timezone
import multiselectfield.db.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('usuario', 'Usuario'), ('protectora', 'Protectora')], default='usuario', max_length=20)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'usuario',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='PerfilProtectora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_protectora', models.CharField(blank=True, max_length=200, null=True)),
                ('cif', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('num_registro_asociacion', models.CharField(blank=True, max_length=100, null=True)),
                ('tipo_entidad_juridica', models.CharField(blank=True, choices=[('asociacion', 'Asociación'), ('fundacion', 'Fundación')], max_length=20, null=True)),
                ('direccion_juridica', models.TextField(blank=True, null=True)),
                ('calle_juridica', models.CharField(blank=True, max_length=200, null=True)),
                ('numero_juridica', models.CharField(blank=True, max_length=10, null=True)),
                ('poblacion_juridica', models.CharField(blank=True, max_length=100, null=True)),
                ('codigo_postal_juridica', models.CharField(blank=True, max_length=10, null=True)),
                ('direccion_refugio', models.TextField(blank=True, null=True)),
                ('calle_refugio', models.CharField(blank=True, max_length=200, null=True)),
                ('numero_refugio', models.CharField(blank=True, max_length=10, null=True)),
                ('poblacion_refugio', models.CharField(blank=True, max_length=100, null=True)),
                ('codigo_postal_refugio', models.CharField(blank=True, max_length=10, null=True)),
                ('web', models.URLField(blank=True, null=True)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('telefono_emergencia', models.CharField(blank=True, max_length=15, null=True)),
                ('capacidad_maxima_animales', models.IntegerField(blank=True, null=True)),
                ('tipo_animal', models.CharField(blank=True, choices=[('perro', 'Perro'), ('gato', 'Gato')], max_length=10, null=True)),
                ('ano_fundacion', models.IntegerField(blank=True, null=True)),
                ('nucleo_zoologico', models.CharField(blank=True, max_length=50, null=True)),
                ('ambito_geografico', models.CharField(blank=True, max_length=200, null=True)),
                ('requisitos_adopcion', models.TextField(blank=True, null=True)),
                ('proceso_adopcion', models.TextField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('servicios', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('recogida', 'Recogida de animales abandonados'), ('alojamiento', 'Alojamiento'), ('esterilizacion', 'Esterilización'), ('localizacion', 'Localización de propietarios'), ('adopcion', 'Adopción')], max_length=57)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_protectora', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Protectora',
                'verbose_name_plural': 'Protectoras',
                'db_table': 'perfil_protectora',
            },
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('barrio', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('foto_perfil', models.ImageField(blank=True, null=True, upload_to='perfils/')),
                ('genero', models.CharField(blank=True, choices=[('M', 'Masculí'), ('F', 'Femení'), ('O', 'Altres'), ('N', 'Preferisc no dir-ho')], max_length=1, null=True)),
                ('especie', models.CharField(blank=True, choices=[('perro', 'Perro'), ('gato', 'Gato')], max_length=10, null=True)),
                ('necesidades_especiales', models.BooleanField(default=False)),
                ('mascota_previa', models.BooleanField(default=False)),
                ('tipo_vivienda', models.CharField(blank=True, choices=[('apartamento', 'Apartamento'), ('casa_pequeña', 'Casa pequeña'), ('casa_grande', 'Casa grande'), ('casa_con_jardin', 'Casa con jardín'), ('finca', 'Finca/Casa rural')], max_length=20, null=True)),
                ('tiene_ninos', models.BooleanField(default=False)),
                ('nivel_actividad_familiar', models.CharField(blank=True, choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta')], max_length=10, null=True)),
                ('preferencias_tamano', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('pequeno', 'Pequeño'), ('mediano', 'Mediano'), ('grande', 'Grande')], max_length=22)),
                ('preferencias_edad', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('cachorro', 'Cachorro'), ('joven', 'Joven'), ('adulto', 'Adulto'), ('senior', 'Senior')], max_length=28)),
                ('preferencias_sexo', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('macho', 'Macho'), ('hembra', 'Hembra')], max_length=12)),
                ('deporte_ofrecible', models.CharField(blank=True, help_text='Deportes/actividades que se le pueden ofrecer (solo para perros)', max_length=200, null=True)),
                ('tiempo_en_casa_para_gatos', models.CharField(blank=True, help_text='Tiempo que pasa en casa (útil para gatos)', max_length=100, null=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_usuario', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil Usuario',
                'verbose_name_plural': 'Perfiles Usuarios',
                'db_table': 'perfil_usuario',
            },
        ),
    ]
