# Generated by Django 5.2.8 on 2025-12-13 19:09

import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='codigo_postal',
            field=models.CharField(blank=True, help_text='Para buscar mascotas cercanas', max_length=10, null=True, verbose_name='Código Postal'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='es_primerizo',
            field=models.BooleanField(default=True, help_text='Marque si nunca ha tenido mascotas antes', verbose_name='¿Es su primera mascota?'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='tiene_gatos',
            field=models.BooleanField(default=False, help_text='Marque si ya tiene gatos en casa', verbose_name='¿Tiene gatos actualmente?'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='tiene_licencia_ppp',
            field=models.BooleanField(default=False, help_text='Licencia para Perros Potencialmente Peligrosos', verbose_name='¿Tiene licencia PPP?'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='tiene_ninos',
            field=models.BooleanField(default=False, help_text='Marque si hay menores de edad en el hogar', verbose_name='¿Tiene niños en casa?'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='tiene_otros_animales',
            field=models.BooleanField(default=False, help_text='Conejos, pájaros, roedores, etc.', verbose_name='¿Tiene otros animales?'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='tiene_perros',
            field=models.BooleanField(default=False, help_text='Marque si ya tiene perros en casa', verbose_name='¿Tiene perros actualmente?'),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='preferencias_convivencia',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('NINOS', 'Apto para convivir con niños'), ('SIN_NINOS', 'Solo adultos / No apto para niños'), ('PERROS', 'Perros (Apto con introducción lenta)'), ('GATOS', 'Gatos (Apto con gatos tranquilos)'), ('SOLO_EL', 'Hogar sin otros animales/Exclusivo'), ('COMPANIA_OBLIGATORIA', 'Compañía Felina/Canina Obligatoria'), ('PRIMERIZOS', 'Dueños Primerizos'), ('EXPERIENCIA', 'Dueños con Experiencia'), ('DUEÑOS_PPP', 'Dueños con Licencia PPP (Para Perros Potencialmente Peligrosos)')], max_length=200, verbose_name='[LEGACY] Apto para Convivir con (Búsqueda)'),
        ),
    ]
