# Generated by Django 5.2.8 on 2025-12-15 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_perfilusuario_codigo_postal_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfilprotectora',
            name='nombre_protectora',
        ),
    ]
